package statsdmetrics

import (
	"github.com/yangxikun/circuit/v3/metrics/statsdmetrics"
)

// generated by goforward github.com/yangxikun/circuit/v3/metrics/statsdmetrics github.com/yangxikun/circuit/metrics/statsdmetrics

// The StatSender interface wraps all the statsd metric methods we care about
type StatSender = statsdmetrics.StatSender

// CommandFactory allows ingesting statsd metrics
type CommandFactory = statsdmetrics.CommandFactory

// ConcurrencyCollector runs as a background routine to collect concurrency stats
type ConcurrencyCollector = statsdmetrics.ConcurrencyCollector

// CircuitMetricsCollector collects opened/closed metrics
type CircuitMetricsCollector = statsdmetrics.CircuitMetricsCollector

// SLOCollector collects SLO level metrics
type SLOCollector = statsdmetrics.SLOCollector

// RunMetricsCollector collects command metrics
type RunMetricsCollector = statsdmetrics.RunMetricsCollector

// FallbackMetricsCollector collects fallback metrics
type FallbackMetricsCollector = statsdmetrics.FallbackMetricsCollector
